# Generated by Django 5.2.8 on 2025-12-07 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appnproylogico', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='AxesAccessattempt',
        ),
        migrations.DeleteModel(
            name='AxesAccessfailurelog',
        ),
        migrations.DeleteModel(
            name='AxesAccesslog',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Oauth2ProviderAccesstoken',
        ),
        migrations.DeleteModel(
            name='Oauth2ProviderApplication',
        ),
        migrations.DeleteModel(
            name='Oauth2ProviderGrant',
        ),
        migrations.DeleteModel(
            name='Oauth2ProviderIdtoken',
        ),
        migrations.DeleteModel(
            name='Oauth2ProviderRefreshtoken',
        ),
        migrations.DeleteModel(
            name='SocialAuthAssociation',
        ),
        migrations.DeleteModel(
            name='SocialAuthCode',
        ),
        migrations.DeleteModel(
            name='SocialAuthNonce',
        ),
        migrations.DeleteModel(
            name='SocialAuthPartial',
        ),
        migrations.DeleteModel(
            name='SocialAuthUsersocialauth',
        ),
        migrations.AlterModelOptions(
            name='asignacionmotomotorista',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='asignacionmotoristafarmacia',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='auditoriageneral',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comuna',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='despacho',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='localfarmacia',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='moto',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='motorista',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='movimientodespacho',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='normalizaciondespacho',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
    ]
