# Generated by Django 5.2.8 on 2025-12-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnproylogico', '0006_moto_add_missing_columns'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='despacho',
            index=models.Index(fields=['codigo_despacho'], name='despacho_codigo__20a9f7_idx'),
        ),
        migrations.AddIndex(
            model_name='despacho',
            index=models.Index(fields=['fecha_registro'], name='despacho_fecha_r_75817e_idx'),
        ),
        migrations.AddIndex(
            model_name='despacho',
            index=models.Index(fields=['estado'], name='despacho_estado_fe4af5_idx'),
        ),
        migrations.AddIndex(
            model_name='despacho',
            index=models.Index(fields=['tipo_despacho'], name='despacho_tipo_de_00ed5b_idx'),
        ),
        migrations.AddIndex(
            model_name='despacho',
            index=models.Index(fields=['farmacia_origen_local_id', 'fecha_registro'], name='despacho_farmaci_d46b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientodespacho',
            index=models.Index(fields=['fecha_movimiento'], name='movimiento__fecha_m_d9b7b8_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientodespacho',
            index=models.Index(fields=['estado_nuevo'], name='movimiento__estado__af1bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientodespacho',
            index=models.Index(fields=['despacho', 'fecha_movimiento'], name='movimiento__despach_fd114d_idx'),
        ),
    ]
