# Generated by Django 5.2.8 on 2025-12-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnproylogico', '0008_auditoria_worm_hash_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='consiente_datos_salud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_consentimiento_salud',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='estado',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='movimientodespacho',
            name='estado_anterior',
            field=models.CharField(blank=True, db_comment='Estado previo', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='movimientodespacho',
            name='estado_nuevo',
            field=models.CharField(db_comment='Estado después del cambio', max_length=12),
        ),
        migrations.AddIndex(
            model_name='asignacionmotomotorista',
            index=models.Index(fields=['moto', 'activa'], name='asignacion__moto_id_f9633b_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionmotomotorista',
            index=models.Index(fields=['motorista', 'activa'], name='asignacion__motoris_1f0d52_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionmotoristafarmacia',
            index=models.Index(fields=['motorista', 'activa'], name='asignacion__motoris_89aa1c_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionmotoristafarmacia',
            index=models.Index(fields=['farmacia', 'activa'], name='asignacion__farmaci_3c26b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='asignacionmotomotorista',
            constraint=models.CheckConstraint(condition=models.Q(('kilometraje_fin__isnull', True), ('kilometraje_fin__gte', models.F('kilometraje_inicio')), _connector='OR'), name='asig_km_fin_gte_inicio_or_null'),
        ),
        migrations.AddConstraint(
            model_name='asignacionmotomotorista',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('activa', True), ('fecha_desasignacion__isnull', True)), ('activa', False), _connector='OR'), name='asig_activa_sin_desasignacion'),
        ),
        migrations.AddConstraint(
            model_name='asignacionmotomotorista',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('moto',), name='uniq_asig_moto_activa'),
        ),
        migrations.AddConstraint(
            model_name='asignacionmotomotorista',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('motorista',), name='uniq_asig_motorista_activa'),
        ),
        migrations.AddConstraint(
            model_name='asignacionmotoristafarmacia',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('activa', True), ('fecha_desasignacion__isnull', True)), ('activa', False), _connector='OR'), name='asig_mf_activa_sin_desasignacion'),
        ),
        migrations.AddConstraint(
            model_name='asignacionmotoristafarmacia',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('motorista', 'farmacia'), name='uniq_asig_mf_activa'),
        ),
        migrations.AddConstraint(
            model_name='despacho',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'ASIGNADO', 'PREPARANDO', 'PREPARADO', 'EN_CAMINO', 'ENTREGADO', 'FALLIDO', 'ANULADO'])), name='desp_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='despacho',
            constraint=models.CheckConstraint(condition=models.Q(('destino_geolocalizacion_validada', False), models.Q(('destino_lat__isnull', False), ('destino_lng__isnull', False)), _connector='OR'), name='desp_geo_valida_requiere_coord'),
        ),
        migrations.AddConstraint(
            model_name='despacho',
            constraint=models.CheckConstraint(condition=models.Q(('receta_devuelta_farmacia', False), ('fecha_devolucion_receta__isnull', False), _connector='OR'), name='desp_receta_devuelta_requiere_fecha'),
        ),
        migrations.AddConstraint(
            model_name='despacho',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'ANULADO'), ('motivo_anulacion__isnull', False), ('fecha_anulacion__isnull', False)), models.Q(('estado', 'ANULADO'), _negated=True), _connector='OR'), name='desp_anulado_requiere_motivo_y_fecha'),
        ),
        migrations.AddConstraint(
            model_name='movimientodespacho',
            constraint=models.CheckConstraint(condition=models.Q(('estado_nuevo__in', ['PENDIENTE', 'ASIGNADO', 'PREPARANDO', 'PREPARADO', 'EN_CAMINO', 'ENTREGADO', 'FALLIDO', 'ANULADO'])), name='mov_estado_nuevo_valido'),
        ),
        migrations.AddConstraint(
            model_name='movimientodespacho',
            constraint=models.CheckConstraint(condition=models.Q(('estado_anterior__in', ['PENDIENTE', 'ASIGNADO', 'PREPARANDO', 'PREPARADO', 'EN_CAMINO', 'ENTREGADO', 'FALLIDO', 'ANULADO']), ('estado_anterior__isnull', True), _connector='OR'), name='mov_estado_anterior_valido_o_null'),
        ),
        migrations.AddConstraint(
            model_name='movimientodespacho',
            constraint=models.CheckConstraint(condition=models.Q(('estado_anterior', models.F('estado_nuevo')), _negated=True), name='mov_estado_no_igual'),
        ),
    ]
