# Generated by Django 5.2.8 on 2025-12-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnproylogico', '0009_usuario_consiente_datos_salud_and_more'),
    ]

    operations = [
    ]
