# Generated by Django 5.2.8 on 2025-12-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnproylogico', '0011_merge_0009_0010'),
    ]

    operations = []
