# Generated by Django 5.2.8 on 2025-12-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnproylogico', '0012_despacho_despacho_motoris_ac6dd0_idx'),
    ]

    operations = []
