# Generated by Django 5.2.8 on 2025-12-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnproylogico', '0013_localfarmacia_localfarmac_fk_regi_a52390_idx_and_more'),
    ]

    operations = []
