# Generated by Django 5.2.8 on 2025-12-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnproylogico', '0014_localfarmacia_farm_lat_rango_and_more'),
    ]

    operations = []
