# Generated by Django 5.2.8 on 2025-12-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnproylogico', '0017_despacho_despacho_motoris_ac6dd0_idx_and_more'),
    ]

    operations = []
