# Generated by Django 5.2.8 on 2025-12-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnproylogico', '0021_despacho_despacho_motoris_ac6dd0_idx_and_more'),
    ]

    operations = [

    ]
